version: 2

jobs:

  test80:
    docker:
      - image: cimg/php:8.0

    steps:
      - checkout
      - run:
          name: Install PHP Extensions
          command: |
            sudo apt-get update -y
            sudo add-apt-repository ppa:ondrej/php -y
            sudo apt-get install php8.0-psr php8.0-yaml -y
            sudo pecl install xdebug

      - run:
          name: Install Phalcon v5.1.1
          command: |
            sudo apt install gcc libpcre3-dev -y
            sudo pecl channel-update pecl.php.net
            sudo pecl install phalcon-5.1.1

      - run: sudo composer selfupdate
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --no-interaction --prefer-source
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: Run Codeception tests
          environment:
            XDEBUG_MODE: coverage
          command: |
            ./vendor/bin/codecept build
            ./vendor/bin/codecept run --coverage --coverage-xml
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov

  test81:
    docker:
      - image: cimg/php:8.1

    steps:
      - checkout
      - run:
          name: Install PHP Extensions
          command: |
            sudo apt-get update -y
            sudo add-apt-repository ppa:ondrej/php -y
            sudo apt-get install php8.1-psr php8.1-yaml -y
            sudo pecl install xdebug

      - run:
          name: Install Phalcon v5.1.1
          command: |
            sudo apt install gcc libpcre3-dev -y
            sudo pecl channel-update pecl.php.net
            sudo pecl install phalcon-5.1.1

      - run: sudo composer selfupdate
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --no-interaction --prefer-source
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: Run Codeception tests
          environment:
            XDEBUG_MODE: coverage
          command: |
            ./vendor/bin/codecept build
            ./vendor/bin/codecept run --coverage --coverage-xml
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov

workflows:
  version: 2
  workflow:
    jobs:
      - test80
      - test81
