# See: https://circleci.com/docs/2.0/language-php/
version: 2

# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/php:7.1.33

    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Install PHP Extensions
          command: |
            sudo apt-get update
            sudo docker-php-ext-install zip
            sudo apt-get install -y libyaml-dev
            sudo pecl install yaml && echo "extension=yaml.so" > /usr/local/etc/php/conf.d/ext-yaml.ini && docker-php-ext-enable yaml

      - run:
          name: Install Phalcon v3.4.5
          command: |
            set -xe && curl -LO https://github.com/phalcon/cphalcon/archive/v3.4.5.tar.gz && tar xzf ${PWD}/v3.4.5.tar.gz
            sudo docker-php-ext-install -j $(getconf _NPROCESSORS_ONLN) ${PWD}/cphalcon-3.4.5/build/php7/64bits

      - run: sudo composer selfupdate
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --no-interaction --prefer-source --dev
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run:
          name: Run Codeception tests
          command: |
            ./vendor/bin/codecept build
            ./vendor/bin/codecept run --coverage --coverage-xml --coverage-html
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov

workflows:
  version: 2
  workflow:
    jobs:
      - test
