version: 2

jobs:
  test:
    docker:
      - image: cimg/php:7.1

    steps:
      - checkout
      - run:
          name: Install PHP Extensions
          command: |
            sudo apt-get update -y
            sudo apt-get install php7.1-yaml php7.1-xdebug

      - run:
          name: Install Phalcon v3.4.5
          command: sudo apt-get install php7.1-phalcon3

      - run: sudo composer selfupdate
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --no-interaction --prefer-source
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: Run Codeception tests
          command: |
            ./vendor/bin/codecept build
            ./vendor/bin/codecept run --coverage --coverage-xml
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov

workflows:
  version: 2
  workflow:
    jobs:
      - test
